language: objective-c
xcode_workspace: MMX-PromiseKit.xcworkspace
xcode_scheme: MMX-PromiseKitTests

cache:
  - bundler
  - cocoapods

before_install:
  - rvm use $RVM_RUBY_VERSION

install:
  - bundle install --without=documentation --path ../travis_bundle_dir
  - gem install cocoapods -v '0.38'
  - pod --version
  - pod install
  -

before_script:
  - brew update
  - brew upgrade xctool

script:
  - xctool -workspace MMX-PromiseKit.xcworkspace -scheme MMX-PromiseKitTests -sdk iphonesimulator test -skip-deps CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

after_success: slather