language: objective-c
xcode_workspace: MMX-PromiseKit.xcworkspace
xcode_scheme: MMX-PromiseKitTests

cache:
  - bundler
  - cocoapods

before_install:
  - rvm use $RVM_RUBY_VERSION

install:
  - bundle install --without=documentation --path ../travis_bundle_dir
  - ../travis_bundle_dir/pod --version
  - ../travis_bundle_dir/pod install

after_success: slather