language: objective-c
xcode_workspace: MMX-PromiseKit.xcworkspace
xcode_scheme: MMX-PromiseKitTests
osx_image: xcode6.4

cache:
  - bundler
  - cocoapods

before_install:
  - rvm use $RVM_RUBY_VERSION

install:
  - gem install cocoapods -v '0.38' --no-ri --no-rdoc
  - gem install slather --no-ri --no-rdoc
  - pod --version
  - pod install

script:
  - xctool build test -workspace MMX-PromiseKit.xcworkspace -scheme MMX-PromiseKitTests -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

after_success: slather